name: Compile Docker Images

on: [push]

jobs:
  main:
    strategy:
      matrix:
        include:
          - arch: amd64
            python: 3.10.12-r0
          - arch: arm64
            python: 3.10.12-r0
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nebraltd/hm-gatewayrs
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=${{ matrix.arch }}-
            type=sha,format=long,prefix=${{ matrix.arch }}-
            type=raw,value=${{ matrix.arch }}-latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: PYTHON_VERSION=${{ matrix.python }}
          push: true
          platforms: linux/${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=nebraltd/hm-gatewayrs:buildcache-${{ matrix.arch }}
          cache-to: type=registry,ref=nebraltd/hm-gatewayrs:buildcache-${{ matrix.arch }},mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  multiarch:
    needs: main
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nebraltd/hm-gatewayrs
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=
            type=sha,format=long,prefix=

      - name: Create multi-arch images
        run: |
          tags=(${{ steps.meta.outputs.tags }})
          docker buildx imagetools create -t ${tags[0]} -t ${tags[1]} -t ${tags[2]} nebraltd/hm-gatewayrs:arm64-${{ github.sha }} nebraltd/hm-gatewayrs:amd64-${{ github.sha }}
          docker buildx imagetools create -t ${tags[3]} -t ${tags[4]} -t ${tags[5]} ghcr.io/nebraltd/hm-gatewayrs:arm64-${{ github.sha }} ghcr.io/nebraltd/hm-gatewayrs:amd64-${{ github.sha }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
