name: Docker Linting

on: [push]

jobs:
  docker-lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
