name: Test

on:
  workflow_dispatch:

jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: Get latest release
        id: gatewayrs
        uses: shawaj/github-action-get-latest-release@patch-1
        with:
          owner: NebraLtd
          repo: hotspot-production-images
          token: ${{ secrets.MR_BUMP }}
          # keep bumping the excludes, right now we only have alpha to track.
          # later we will start tracking beta and finally release
          excludes: prerelease, draft
      - name: Update gateway rs release if required
        run: |
          # Get the latest GA release and update if necessary
          LATEST_GA=${{ steps.gatewayrs.outputs.release }}
          GITHUB_BRANCH=$( echo "${{ github.ref }}" | sed 's/refs\/heads\///g' )
          
          echo "LATEST_GA=$LATEST_GA" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> $GITHUB_ENV
          if grep -q "$LATEST_GA" Dockerfile; then
            echo "We're on the latest Helium gateway-rs release $LATEST_GA."
            exit 0
          else
            echo "We're not on the latest Helium gateway-rs release. Updating to $LATEST_GA."
            sed -i -E 's/GATEWAY_RS_RELEASE=.*/GATEWAY_RS_RELEASE='$LATEST_GA'/g' Dockerfile
            UPDATED=true
            echo "UPDATED=$UPDATED" >> $GITHUB_ENV
            exit 0
          fi
